### PR TITLE
Make rubocop happy, no warning, and fix add

### PR DESCRIPTION
**Pull request by programmin1**
Fix warning for rubocop.

### CODE REVIEW

**Comment by casto101** [comment]
LGTM 👍

**Comment by conroywhitney** [comment]
Hey @programmin1. Thanks for submitting this pull request!

You're right -- this does fix both the linter, and it seems, the problem that was identified in Issue #5.

Would you please add some tests that show how the `add` method was broken before, and prove that it is working now?

Thanks!

**Comment by seanculver** [comment]
It looks like your PR'ng from the master branch on your fork, this might cause issues later on if this PR does not get merged. We would recommend that you create a feature branch on your fork.

Thanks!

**Comment by conroywhitney** [comment]
Actually, I'm going to close this PR since #10 fixed both the `add` method as well as got rid of the related `rubocop` errors. Thanks for submitting this @programmin1!

**Pull request closed without merging**
