### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by seanculver**
I think we need this to be clear of what our expectations are for contributing and participating in this project.

### CODE REVIEW

**Comment by conroywhitney** [comment]
Hey @seanculver -- can we discuss which CoC we plan to implement in #17?

As I mention in there, I'm not personally sure I'd like to use the Contributor Covenant for this project. Can we talk about it over there?

**Comment by seanculver** [comment]
@conroywhitney Sure, let's keep the discussion going. We should address anything we see as inappropriate before we merge this then.

**Comment by conroywhitney** [comment]
Thanks @seanculver! Closing in favour of #20.

**Comment by conroywhitney** [comment]
^-- per discussion in Issue #17

**Pull request closed without merging**
